hlxsites/delta

- blocks/banner/banner.css
- blocks/banner/banner.js
- blocks/header/header.css
- styles/styles.css
Fix #6 
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/
- After: https://issue-6--delta--hlxsites.hlx.page/
> Hero banner with random images

- blocks/header/header.css
- styles/styles.css
Fix #18 
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/
- After: https://issue-18--delta--hlxsites.hlx.page/
> Styling main intro heading 

- blocks/footer/footer.css
- blocks/footer/footer.js
- blocks/header/header.css
- styles/styles.css
updated footer css and some linting to make the PR work
https://footer-touchup--delta--hlxsites.hlx.page/
vs.
https://main--delta--hlxsites.hlx.page/
> footer touchup

- blocks/footer/footer.css
- blocks/footer/footer.js
Fix #26 
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/
- After: https://issue-26--delta--hlxsites.hlx.page/
> Footer style for smaller viewports

- blocks/banner/banner.js
- blocks/booking-widget/booking-widget.css
- blocks/booking-widget/booking-widget.js
- scripts/lib-franklin.js
- scripts/scripts.js
- styles/styles.css
Adding a minimal booking widget
Fix #7 
Test URLs:
- Before: https://main--delta--hlxsites.hlx.live/
- After: https://issue-7--delta--hlxsites.hlx.live/
> feat: add booking widget

- us/en/skymiles/blocks/header/header.css
- us/en/skymiles/blocks/hero/hero.css
- us/en/skymiles/icons/info-supergraphic-delta-mark.svg
- us/en/skymiles/scripts/scripts.js
- us/en/skymiles/styles/styles.css
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--<repo>--<owner>.hlx.page/
- After: https://<branch>--<repo>--<owner>.hlx.page/
> feat: add basic styles for skymiles pages

- us/en/skymiles/blocks/columns/columns.css
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/
- After: https://format-columns--delta--hlxsites.hlx.page/
> Formatting the icons to be the same height and align center

- us/en/skymiles/blocks/cards/cards.css
Fix #50 
Test URLs:
- After: https://issue-50--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> Cards style touchup

- us/en/skymiles/blocks/footer/footer.css
- us/en/skymiles/blocks/footer/footer.js
Fix #61 
Test URLs:
- After: https://issue-61--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> feat: clean up the CSS for footer search section

- us/en/skymiles/blocks/hero/hero.css
- us/en/skymiles/blocks/hero/hero.js
- us/en/skymiles/scripts/scripts.js
Fix #40 
Test URLs:
- After: https://issue40--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> feat: style hero block

- us/en/skymiles/blocks/columns/columns.css
- us/en/skymiles/scripts/scripts.js
- us/en/skymiles/styles/styles.css
Fix #41 
Test URLs:
- Before: https://main--delta--hxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
- After: https://issue-41--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
Note: This PR also has a fix for buttons "DISCOVER ALL CARDS" and "Benefits Terms"
> Style for CTA section

- us/en/skymiles/blocks/columns/columns.css
- us/en/skymiles/scripts/scripts.js
Fix #49 
Test URLs:
- After: https://issue-49--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> Columns block styling

- us/en/skymiles/blocks/blade/blade.css
- us/en/skymiles/scripts/scripts.js
- us/en/skymiles/styles/styles.css
Automatically decorate inline accordions based on the presence of a `p>.icon-toggle` put in the content via `:toggle:`.
Fix #58
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/us/en/skymiles/medallion-program/diamond-medallion-status
- After: https://issue-58--delta--hlxsites.hlx.page/drafts/alex/import/us/en/skymiles/medallion-program/diamond-medallion-status
> feat: inline accordion

- us/en/skymiles/blocks/columns/columns.css
Fix #68 
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/drafts/asthabharga/us/en/skymiles/how-to-earn-miles/exception-fares
- After: https://issue-68--delta--hlxsites.hlx.page/drafts/asthabharga/us/en/skymiles/how-to-earn-miles/exception-fares
> Emphasized columns styling

- us/en/skymiles/scripts/scripts.js
- us/en/skymiles/styles/styles.css
Fix #90 
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/drafts/asthabharga/us/en/skymiles/how-to-use-miles/overview
- After: https://issue-90--delta--hlxsites.hlx.page/drafts/asthabharga/us/en/skymiles/how-to-use-miles/overview
> Heading style fix in CTA section

- us/en/skymiles/blocks/pager/pager.css
- us/en/skymiles/blocks/pager/pager.js
- us/en/skymiles/scripts/scripts.js
- us/en/skymiles/styles/styles.css
Fix #37 
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/airline-partners
- After: https://issue-37--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/airline-partners
> feat: style the highlight section above the footer

- us/en/skymiles/blocks/columns/columns.css
Fix #104 
Test URLs:
- Before: https://main--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/exception-fares
- After: https://issue-104--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/exception-fares
> fixed the width of table with two columns

- us/en/skymiles/scripts/scripts.js
- us/en/skymiles/styles/styles.css
Fix #114 
Test URLs:
- After: https://issue-114--delta--hlxsites.hlx.page/us/en/skymiles/overview
> fix: badge position on landing page

- us/en/skymiles/scripts/scripts.js
- us/en/skymiles/styles/styles.css
Add quick navigation links for accessibility compliance.
Fix #115 
Test URLs:
- After: https://issue-115--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> feat: add accessibility quick links

- us/en/skymiles/blocks/cards/cards.css
- us/en/skymiles/blocks/columns/columns.css
- us/en/skymiles/styles/styles.css
Fix #123 
Test URLs:
- After: https://issue-123--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> Fixed styling in columns and cards blocks to match original pages

- us/en/skymiles/blocks/section-nav/aria-menu.js
- us/en/skymiles/blocks/section-nav/section-nav.css
- us/en/skymiles/blocks/section-nav/section-nav.js
- us/en/skymiles/styles/styles.css
Adds support for WCAG compliant menus and implement the section navigation with it.
Inline search suggestion is tackled separately in #131.
Fix #127 
Test URLs:
- After: https://issue-127--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> feat: WCAG compliance for section nav menu

- us/en/skymiles/blocks/footer/aria-dialog.js
- us/en/skymiles/blocks/footer/footer.css
- us/en/skymiles/blocks/footer/footer.js
Adds inline search suggestions to the footer search dialog.
Fix #131 
Test URLs:
- After: https://issue-131--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> feat: add inline search suggestions and fix dialog focus handler

- us/en/skymiles/scripts/scripts.js
Fix #<gh-issue-id>
Test URLs:
- After: https://issue-143--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> issue-143 the alt language version tags are missing

- us/en/skymiles/blocks/accordion/accordion.css
- us/en/skymiles/blocks/blade/blade.css
- us/en/skymiles/blocks/blade/blade.js
- us/en/skymiles/blocks/columns/columns.css
- us/en/skymiles/blocks/section-nav/section-nav.css
- us/en/skymiles/blocks/section-nav/section-nav.js
- us/en/skymiles/blocks/table/table.css
- us/en/skymiles/blocks/tabs/tabs.css
- us/en/skymiles/blocks/toc/toc.css
- us/en/skymiles/scripts/lib-franklin.js
- us/en/skymiles/scripts/scripts.js
- us/en/skymiles/styles/styles.css
Also fixes a plethora of minor styling issues.
Fix #156
Test URLs:
- After: https://issue-156--delta--hlxsites.hlx.page/us/en/skymiles/how-to-earn-miles/overview
> feat: large sections need to be explicitly decorated
